export const SACAR_PRODUCTO = 'SACAR_PRODUCTO';
export const COMPROBAR_SACAR_PRODUCTO = 'COMPROBAR_SACAR_PRODUCTO';
export const INSERTAR_DINERO = 'INSERTAR_DINERO';
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS';
export const PEDIR_PRODUCTOS = 'PEDIR_PRODUCTOS';
